#!/bin/sh

[ -d .git ] || { echo 'execute me in root repository dir (where .git subdir is located)!' 1>&2; exit 1; }

D=.git/auto-sync
mkdir -p $D

_local_change () {
    git add -A
    git commit -m 'x' || true

    for p in $peers; do
        git push $p +$lclbranch:$lclbranch
    done || true
}

_local_merge () {
    local ml=$D/merge.log
    local conflicted=0
    for rmtbranch in $(git branch | cut -c3- | grep -v $lclbranch); do
        echo `pwd`: git merge $rmtbranch
        git merge $rmtbranch > $ml 2>&1 || true
        cat $ml
        echo ===
        grep 'Cannot merge binary files:' $ml | \
            cut -c37- | cut -d'(' -f1 | { 
                files=
                while read fn; do
                    echo "conflict: $fn"
                    conflicted=1
                    rm $fn
                    { git checkout $lclbranch $fn && mv $fn $fn.$lclbranch; } || git checkout $lclbranch $fn.$lclbranch
                    { git checkout $rmtbranch $fn && mv $fn $fn.$rmtbranch; } || git checkout $rmtbranch $fn.$rmtbranch
                    files="$files $fn"
                done
                if [ "$conflicted" = "1" ]; then
                    git ls-files -u
                    git add -A
                    git commit -m "Merge branch '$rmtbranch' into '$lclbranch'; conflicts:$files"
                fi
            } || true
    done
}

_remote_change () {
    peers=$(cat $D/peers)
    for p in $peers; do
        git fetch $* $p
    done
    #touch $D/remote-change
}

init () {
    set -e
    [ "$1" = "--shallow" ] && { pullopts=--depth=1; shift; }
    echo '* -diff' >> .git/info/attributes
    echo "ref: refs/heads/$1" > .git/HEAD
    echo "$1" > $D/branch
    shift
    echo "$*" > $D/peers
    cat > .git/hooks/post-receive <<EOF
#!/bin/sh
touch auto-sync/remote-change
rm auto-sync/block 2> /dev/null
EOF
    chmod +x .git/hooks/post-receive
    lclbranch=$(cat $D/branch)
    peers=$(cat $D/peers)
    for p in $peers; do
        git pull $pullopts $p && {
            b=$(git branch | cut -c3- | head -n1)
            git reset --hard
            echo "initialized local branch $lclbranch from $p:$b"
            break
        }
    done || { echo "warning: local branch $lclbranch not initialized properly"; exit 1; }
}

_monitor_dir () {
    local x
    inotifywait -q -m -e CLOSE_WRITE -e DELETE -e MOVED_TO . | while read x; do
        touch $D/local-change
        _unblock
    done
}

_block () {
    inotifywait -q -e DELETE $D/block
    touch $D/block
}

_unblock () {
    rm $D/block 2> /dev/null || true
}

once () {
    lclbranch=$(cat $D/branch)
    peers=$(cat $D/peers)

    echo once: $lclbranch

    [ "$1" != "--skip-remote-change" ] && _remote_change
    _local_merge
    _local_change
}

_periodic () {
    while true; do
        sleep 10
        touch $D/periodic
        _unblock
    done
}

run_with_inotify () {
    once

    lclbranch=$(cat $D/branch)
    peers=$(cat $D/peers)

    touch $D/block

    trap "kill -TERM -$$" EXIT

    [ "$1" = "--periodic" ] && { _periodic & }
    _monitor_dir &

    while true; do
        _block
        echo unblocked
        if [ -e $D/local-change ]; then
            rm $D/local-change
            _local_change
            [ "$GIT_A_S_CHANGE" != "" ] && { eval "$GIT_A_S_CHANGE"; }
        fi
        if [ -e $D/remote-change ]; then
            rm $D/remote-change
            _local_merge
            _local_change
            [ "$GIT_A_S_CHANGE" != "" ] && { eval "$GIT_A_S_CHANGE"; }
        fi
        if [ -e $D/periodic ]; then
            rm $D/periodic
            once
        fi
    done
}

run_with_polling () {
    local period=$1
    shift
    [ "$period" = "" ] && { period=60; }
    while true; do 
        once $*
        sleep $period
    done
}

run () { run_with_inotify "$*"; }

eval "$*"

